#! /usr/bin/env bash

set -eu -o pipefail

#
# Run the update.lambda_handler locally in a docker container
#

NAME="antivirus-update"

docker run --rm -d \
  -v "$(pwd):/var/task" \
  -e AV_DEFINITION_PATH \
  -e AV_DEFINITION_S3_BUCKET \
  -e AV_DEFINITION_S3_PREFIX \
  -e AWS_ACCESS_KEY_ID \
  -e AWS_DEFAULT_REGION \
  -e AWS_REGION \
  -e AWS_SECRET_ACCESS_KEY \
  -e AWS_SESSION_TOKEN \
  --name="${NAME}" \
  bucket-antivirus-function:latest update.lambda_handler
trap 'docker kill ${NAME}' SIGINT
echo "Press CTRL-C to exit"
sleep 0.5
docker exec "${NAME}" curl -s -XPOST "http://localhost:8080/2015-03-31/functions/function/invocations" -d '{}'
docker logs -f "${NAME}"
